"use client";
// ============================================================
// Central icon module — professional Phosphor icon set.
// Re-exported under the previous names so usage stays unchanged.
// Swap the right-hand Phosphor icons here to restyle globally.
// ============================================================
export {
  WarningCircle as AlertCircle,
  ArrowLeft,
  ArrowRight,
  Buildings as Building2,
  CalendarBlank as CalendarClock,
  Check,
  CheckCircle as CheckCircle2,
  CheckSquare,
  Clock,
  CaretDown,
  CaretRight,
  ChatCircleDots as Feedback,
  Cpu,
  Database,
  Columns,
  DownloadSimple as Download,
  DotsThreeVertical as MoreVertical,
  FileText,
  Flag,
  Folder,
  FolderOpen,
  FolderPlus,
  Kanban as FolderKanban,
  Globe,
  House as Home,
  Image,
  Lightning,
  ListDashes as ListView,
  MagnifyingGlass as Search,
  PencilSimple as Pencil,
  Pause,
  Robot,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  LinkSimple as Link2,
  ListChecks,
  SignOut as LogOut,
  EnvelopeSimple as Mail,
  List as Menu,
  ChatCircle as MessageSquare,
  Sidebar as PanelLeft,
  Paperclip,
  Play,
  Plus,
  ArrowCounterClockwise as RotateCcw,
  PaperPlaneRight as Send,
  GearSix as Settings,
  Sparkle as Sparkles,
  Note as StickyNote,
  Trash as Trash2,
  UploadSimple as Upload,
  User,
  UsersThree as Users,
  X,
} from "@phosphor-icons/react";
